server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Route all React paths back to index.html (SPA support)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
